{
 "title": "Algorithm Metrics(Incremental Learning)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "AI_task_name",
    "label": "AI Task Name",
    "query": {
     "query": "label_values(kube_sedna_io_v1alpha1_IncrementalLearningJob_StageConditionStatus, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Algorithm Metrics (Incremental Learning)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current Task Stage\t",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_TaskStage{name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageConditionStatus{name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IterationNo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by(name) (kube_sedna_io_v1alpha1_IncrementalLearningJob_StageDetails{stage=\"Train\", type=\"Waiting\", name=\"$AI_task_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Samples",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_DatasetInfo{name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_Dataset_numberOfSamples",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TrainOutputModelUrl",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageDetails{stage=\"Train\", type=\"Ready\", name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TrainLoss",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageDetails{stage=\"Train\", type=\"Completed\", name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EvalNewModelUrl",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageDetails{stage=\"Eval\", type=\"Ready\", name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IterationHardSampleNum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "Incremental_HardSamples{hardSample=\"True\"}"
    }
   ]
  },
  {
   "title": "AccuracyMetricForModels",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageDetails{stage=\"Eval\", type=\"Completed\", name=\"$AI_task_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}