{
 "title": "Common System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Common System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Running",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "kube_pod_status_phase", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated"
    }
   ]
  },
  {
   "title": "StageConditionStatus",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_JointInferenceService_StageConditionStatus"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StageConditionStatus"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_FederatedLearningJob_StageConditionStatus"
    }
   ]
  },
  {
   "title": "Start Time of AI Tasks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_JointInferenceService_StartTime"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_IncrementalLearningJob_StartTime",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_sedna_io_v1alpha1_FederatedLearningJob_StartTime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataset",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_sedna_io_v1alpha1_Dataset_numberOfSamples",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}