{
 "title": "lifelonglearning-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model deploy status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "task_status", "legendFormat": "task-{{task_id}}" }
   ]
  },
  {
   "title": "Deploy status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deploy_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Task num",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "targets": [
    { "expr": "task_num", "legendFormat": "task-{{id}}-{{attr}}" }
   ]
  },
  {
   "title": "Deployed model num",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 5 },
   "targets": [
    { "expr": "know_task_num", "legendFormat": "total" }
   ]
  },
  {
   "title": "Task sample num",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    { "expr": "task_sample_num", "legendFormat": "task-{{id}}" }
   ]
  },
  {
   "title": "Task relationship",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "task_relation_ship",
     "legendFormat": "grp-{{grp_id}}-task-{{task_id}}"
    }
   ]
  },
  {
   "title": "Model URL",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "task_status" }
   ]
  },
  {
   "title": "Precision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "expr": "Precision{}" }
   ]
  },
  {
   "title": "Recall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "Recall{}" }
   ]
  },
  {
   "title": "File nums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "files_with_suffix_num{}" }
   ]
  }
 ]
}