/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeedge/sedna/pkg/apis/sedna/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNNPartitioningServices implements DNNPartitioningServiceInterface
type FakeDNNPartitioningServices struct {
	Fake *FakeSednaV1alpha1
	ns   string
}

var dnnpartitioningservicesResource = schema.GroupVersionResource{Group: "sedna.io", Version: "v1alpha1", Resource: "dnnpartitioningservices"}

var dnnpartitioningservicesKind = schema.GroupVersionKind{Group: "sedna.io", Version: "v1alpha1", Kind: "DNNPartitioningService"}

// Get takes name of the dNNPartitioningService, and returns the corresponding dNNPartitioningService object, and an error if there is any.
func (c *FakeDNNPartitioningServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DNNPartitioningService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnnpartitioningservicesResource, c.ns, name), &v1alpha1.DNNPartitioningService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNNPartitioningService), err
}

// List takes label and field selectors, and returns the list of DNNPartitioningServices that match those selectors.
func (c *FakeDNNPartitioningServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DNNPartitioningServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnnpartitioningservicesResource, dnnpartitioningservicesKind, c.ns, opts), &v1alpha1.DNNPartitioningServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DNNPartitioningServiceList{ListMeta: obj.(*v1alpha1.DNNPartitioningServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.DNNPartitioningServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNNPartitioningServices.
func (c *FakeDNNPartitioningServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnnpartitioningservicesResource, c.ns, opts))

}

// Create takes the representation of a dNNPartitioningService and creates it.  Returns the server's representation of the dNNPartitioningService, and an error, if there is any.
func (c *FakeDNNPartitioningServices) Create(ctx context.Context, dNNPartitioningService *v1alpha1.DNNPartitioningService, opts v1.CreateOptions) (result *v1alpha1.DNNPartitioningService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnnpartitioningservicesResource, c.ns, dNNPartitioningService), &v1alpha1.DNNPartitioningService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNNPartitioningService), err
}

// Update takes the representation of a dNNPartitioningService and updates it. Returns the server's representation of the dNNPartitioningService, and an error, if there is any.
func (c *FakeDNNPartitioningServices) Update(ctx context.Context, dNNPartitioningService *v1alpha1.DNNPartitioningService, opts v1.UpdateOptions) (result *v1alpha1.DNNPartitioningService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnnpartitioningservicesResource, c.ns, dNNPartitioningService), &v1alpha1.DNNPartitioningService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNNPartitioningService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNNPartitioningServices) UpdateStatus(ctx context.Context, dNNPartitioningService *v1alpha1.DNNPartitioningService, opts v1.UpdateOptions) (*v1alpha1.DNNPartitioningService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnnpartitioningservicesResource, "status", c.ns, dNNPartitioningService), &v1alpha1.DNNPartitioningService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNNPartitioningService), err
}

// Delete takes name of the dNNPartitioningService and deletes it. Returns an error if one occurs.
func (c *FakeDNNPartitioningServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dnnpartitioningservicesResource, c.ns, name), &v1alpha1.DNNPartitioningService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNNPartitioningServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnnpartitioningservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DNNPartitioningServiceList{})
	return err
}

// Patch applies the patch and returns the patched dNNPartitioningService.
func (c *FakeDNNPartitioningServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNNPartitioningService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnnpartitioningservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DNNPartitioningService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNNPartitioningService), err
}
