/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeedge/sedna/pkg/apis/sedna/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReidJobs implements ReidJobInterface
type FakeReidJobs struct {
	Fake *FakeSednaV1alpha1
	ns   string
}

var reidjobsResource = schema.GroupVersionResource{Group: "sedna.io", Version: "v1alpha1", Resource: "reidjobs"}

var reidjobsKind = schema.GroupVersionKind{Group: "sedna.io", Version: "v1alpha1", Kind: "ReidJob"}

// Get takes name of the reidJob, and returns the corresponding reidJob object, and an error if there is any.
func (c *FakeReidJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReidJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(reidjobsResource, c.ns, name), &v1alpha1.ReidJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReidJob), err
}

// List takes label and field selectors, and returns the list of ReidJobs that match those selectors.
func (c *FakeReidJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReidJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(reidjobsResource, reidjobsKind, c.ns, opts), &v1alpha1.ReidJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReidJobList{ListMeta: obj.(*v1alpha1.ReidJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReidJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested reidJobs.
func (c *FakeReidJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(reidjobsResource, c.ns, opts))

}

// Create takes the representation of a reidJob and creates it.  Returns the server's representation of the reidJob, and an error, if there is any.
func (c *FakeReidJobs) Create(ctx context.Context, reidJob *v1alpha1.ReidJob, opts v1.CreateOptions) (result *v1alpha1.ReidJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(reidjobsResource, c.ns, reidJob), &v1alpha1.ReidJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReidJob), err
}

// Update takes the representation of a reidJob and updates it. Returns the server's representation of the reidJob, and an error, if there is any.
func (c *FakeReidJobs) Update(ctx context.Context, reidJob *v1alpha1.ReidJob, opts v1.UpdateOptions) (result *v1alpha1.ReidJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(reidjobsResource, c.ns, reidJob), &v1alpha1.ReidJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReidJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReidJobs) UpdateStatus(ctx context.Context, reidJob *v1alpha1.ReidJob, opts v1.UpdateOptions) (*v1alpha1.ReidJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(reidjobsResource, "status", c.ns, reidJob), &v1alpha1.ReidJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReidJob), err
}

// Delete takes name of the reidJob and deletes it. Returns an error if one occurs.
func (c *FakeReidJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(reidjobsResource, c.ns, name), &v1alpha1.ReidJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReidJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(reidjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReidJobList{})
	return err
}

// Patch applies the patch and returns the patched reidJob.
func (c *FakeReidJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReidJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(reidjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ReidJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReidJob), err
}
