name: "odom"
manufacturer: ""
series: ""
description: ""
driver:
  version: "ros1"
  type: "ros"
  name: "ros_common_driver"
data:
  support: true
  target: "/odom"
  pose: "initialpose"
  mapframe: "map"  # world frame name
  actual_hz: 10
  origin_hz: 200
requirement:  # Used to generate roslaunch files.
  - nav_msgs
