// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type DatasetExpansion interface{}

type FederatedLearningJobExpansion interface{}

type IncrementalLearningJobExpansion interface{}

type JointInferenceServiceExpansion interface{}

type ModelExpansion interface{}
