apiVersion: v1
kind: Service
metadata:
  name: kb
  namespace: sedna
spec:
  selector:
    sedna: kb
  type: NodePort
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 9020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb
  labels:
    sedna: kb
  namespace: sedna
spec:
  replicas: 1
  selector:
    matchLabels:
      sedna: kb
  template:
    metadata:
      labels:
        sedna: kb
    spec:
      nodeSelector:
        # only schedule to master node
        node-role.kubernetes.io/master: ""
      serviceAccountName: sedna
      containers:
      - name: kb
        image: swr.cn-southwest-2.myhuaweicloud.com/sedna-test/sedna/kb:v0.0.1
        command: ["python", "/code/lib/sedna/service/run_kb.py"]
        env:
          - name: LIFELONG_KB_URL
            value: "sqlite:///db/lifelong_kb.sqlite3"
        volumeMounts:
        - name: lifelong-kb-url
          mountPath: /db
        resources:
          requests:
            memory: 256Mi
            cpu: 512m
          limits:
            memory: 512Mi
      volumes:
        - name: lifelong-kb-url
          hostPath:
            path: /rootfs
            type: DirectoryOrCreate
