# permissions for end users to view inferencemodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferencemodel-viewer-role
rules:
- apiGroups:
  - sedna.io
  resources:
  - inferencemodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sedna.io
  resources:
  - inferencemodels/status
  verbs:
  - get
