# permissions for end users to edit inferencemodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferencemodel-editor-role
rules:
- apiGroups:
  - sedna.io
  resources:
  - inferencemodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sedna.io
  resources:
  - inferencemodels/status
  verbs:
  - get
