//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregationWorker) DeepCopyInto(out *AggregationWorker) {
	*out = *in
	out.Model = in.Model
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregationWorker.
func (in *AggregationWorker) DeepCopy() *AggregationWorker {
	if in == nil {
		return nil
	}
	out := new(AggregationWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigModel) DeepCopyInto(out *BigModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigModel.
func (in *BigModel) DeepCopy() *BigModel {
	if in == nil {
		return nil
	}
	out := new(BigModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudModel) DeepCopyInto(out *CloudModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudModel.
func (in *CloudModel) DeepCopy() *CloudModel {
	if in == nil {
		return nil
	}
	out := new(CloudModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWorker) DeepCopyInto(out *CloudWorker) {
	*out = *in
	out.Model = in.Model
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWorker.
func (in *CloudWorker) DeepCopy() *CloudWorker {
	if in == nil {
		return nil
	}
	out := new(CloudWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningCloudWorker) DeepCopyInto(out *DNNPartitioningCloudWorker) {
	*out = *in
	out.Model = in.Model
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningCloudWorker.
func (in *DNNPartitioningCloudWorker) DeepCopy() *DNNPartitioningCloudWorker {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningCloudWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningEdgeWorker) DeepCopyInto(out *DNNPartitioningEdgeWorker) {
	*out = *in
	out.Model = in.Model
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningEdgeWorker.
func (in *DNNPartitioningEdgeWorker) DeepCopy() *DNNPartitioningEdgeWorker {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningEdgeWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningService) DeepCopyInto(out *DNNPartitioningService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningService.
func (in *DNNPartitioningService) DeepCopy() *DNNPartitioningService {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNNPartitioningService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningServiceCondition) DeepCopyInto(out *DNNPartitioningServiceCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningServiceCondition.
func (in *DNNPartitioningServiceCondition) DeepCopy() *DNNPartitioningServiceCondition {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningServiceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningServiceList) DeepCopyInto(out *DNNPartitioningServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNNPartitioningService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningServiceList.
func (in *DNNPartitioningServiceList) DeepCopy() *DNNPartitioningServiceList {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNNPartitioningServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningServiceSpec) DeepCopyInto(out *DNNPartitioningServiceSpec) {
	*out = *in
	in.DNNPartitioningEdgeWorker.DeepCopyInto(&out.DNNPartitioningEdgeWorker)
	in.DNNPartitioningCloudWorker.DeepCopyInto(&out.DNNPartitioningCloudWorker)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningServiceSpec.
func (in *DNNPartitioningServiceSpec) DeepCopy() *DNNPartitioningServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNNPartitioningServiceStatus) DeepCopyInto(out *DNNPartitioningServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DNNPartitioningServiceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNNPartitioningServiceStatus.
func (in *DNNPartitioningServiceStatus) DeepCopy() *DNNPartitioningServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DNNPartitioningServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dataset) DeepCopyInto(out *Dataset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dataset.
func (in *Dataset) DeepCopy() *Dataset {
	if in == nil {
		return nil
	}
	out := new(Dataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dataset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetList) DeepCopyInto(out *DatasetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dataset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetList.
func (in *DatasetList) DeepCopy() *DatasetList {
	if in == nil {
		return nil
	}
	out := new(DatasetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatasetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetSpec) DeepCopyInto(out *DatasetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetSpec.
func (in *DatasetSpec) DeepCopy() *DatasetSpec {
	if in == nil {
		return nil
	}
	out := new(DatasetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetStatus) DeepCopyInto(out *DatasetStatus) {
	*out = *in
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetStatus.
func (in *DatasetStatus) DeepCopy() *DatasetStatus {
	if in == nil {
		return nil
	}
	out := new(DatasetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployModel) DeepCopyInto(out *DeployModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployModel.
func (in *DeployModel) DeepCopy() *DeployModel {
	if in == nil {
		return nil
	}
	out := new(DeployModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploySpec) DeepCopyInto(out *DeploySpec) {
	*out = *in
	out.Model = in.Model
	in.Trigger.DeepCopyInto(&out.Trigger)
	in.HardExampleMining.DeepCopyInto(&out.HardExampleMining)
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploySpec.
func (in *DeploySpec) DeepCopy() *DeploySpec {
	if in == nil {
		return nil
	}
	out := new(DeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeModel) DeepCopyInto(out *EdgeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeModel.
func (in *EdgeModel) DeepCopy() *EdgeModel {
	if in == nil {
		return nil
	}
	out := new(EdgeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeWorker) DeepCopyInto(out *EdgeWorker) {
	*out = *in
	out.Model = in.Model
	in.HardExampleMining.DeepCopyInto(&out.HardExampleMining)
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeWorker.
func (in *EdgeWorker) DeepCopy() *EdgeWorker {
	if in == nil {
		return nil
	}
	out := new(EdgeWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalSpec) DeepCopyInto(out *EvalSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalSpec.
func (in *EvalSpec) DeepCopy() *EvalSpec {
	if in == nil {
		return nil
	}
	out := new(EvalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FEDeploy) DeepCopyInto(out *FEDeploy) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FEDeploy.
func (in *FEDeploy) DeepCopy() *FEDeploy {
	if in == nil {
		return nil
	}
	out := new(FEDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FLJobCondition) DeepCopyInto(out *FLJobCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FLJobCondition.
func (in *FLJobCondition) DeepCopy() *FLJobCondition {
	if in == nil {
		return nil
	}
	out := new(FLJobCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FLJobSpec) DeepCopyInto(out *FLJobSpec) {
	*out = *in
	in.AggregationWorker.DeepCopyInto(&out.AggregationWorker)
	if in.TrainingWorkers != nil {
		in, out := &in.TrainingWorkers, &out.TrainingWorkers
		*out = make([]TrainingWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.PretrainedModel = in.PretrainedModel
	in.Transmitter.DeepCopyInto(&out.Transmitter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FLJobSpec.
func (in *FLJobSpec) DeepCopy() *FLJobSpec {
	if in == nil {
		return nil
	}
	out := new(FLJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FLJobStatus) DeepCopyInto(out *FLJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]FLJobCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FLJobStatus.
func (in *FLJobStatus) DeepCopy() *FLJobStatus {
	if in == nil {
		return nil
	}
	out := new(FLJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedLearningJob) DeepCopyInto(out *FederatedLearningJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedLearningJob.
func (in *FederatedLearningJob) DeepCopy() *FederatedLearningJob {
	if in == nil {
		return nil
	}
	out := new(FederatedLearningJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedLearningJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedLearningJobList) DeepCopyInto(out *FederatedLearningJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FederatedLearningJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedLearningJobList.
func (in *FederatedLearningJobList) DeepCopy() *FederatedLearningJobList {
	if in == nil {
		return nil
	}
	out := new(FederatedLearningJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedLearningJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardExampleMining) DeepCopyInto(out *HardExampleMining) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ParaSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardExampleMining.
func (in *HardExampleMining) DeepCopy() *HardExampleMining {
	if in == nil {
		return nil
	}
	out := new(HardExampleMining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ILDataset) DeepCopyInto(out *ILDataset) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ILDataset.
func (in *ILDataset) DeepCopy() *ILDataset {
	if in == nil {
		return nil
	}
	out := new(ILDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ILJobCondition) DeepCopyInto(out *ILJobCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ILJobCondition.
func (in *ILJobCondition) DeepCopy() *ILJobCondition {
	if in == nil {
		return nil
	}
	out := new(ILJobCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ILJobSpec) DeepCopyInto(out *ILJobSpec) {
	*out = *in
	out.Dataset = in.Dataset
	out.InitialModel = in.InitialModel
	in.TrainSpec.DeepCopyInto(&out.TrainSpec)
	in.EvalSpec.DeepCopyInto(&out.EvalSpec)
	in.DeploySpec.DeepCopyInto(&out.DeploySpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ILJobSpec.
func (in *ILJobSpec) DeepCopy() *ILJobSpec {
	if in == nil {
		return nil
	}
	out := new(ILJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ILJobStatus) DeepCopyInto(out *ILJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ILJobCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ILJobStatus.
func (in *ILJobStatus) DeepCopy() *ILJobStatus {
	if in == nil {
		return nil
	}
	out := new(ILJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncrementalLearningJob) DeepCopyInto(out *IncrementalLearningJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncrementalLearningJob.
func (in *IncrementalLearningJob) DeepCopy() *IncrementalLearningJob {
	if in == nil {
		return nil
	}
	out := new(IncrementalLearningJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncrementalLearningJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncrementalLearningJobList) DeepCopyInto(out *IncrementalLearningJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncrementalLearningJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncrementalLearningJobList.
func (in *IncrementalLearningJobList) DeepCopy() *IncrementalLearningJobList {
	if in == nil {
		return nil
	}
	out := new(IncrementalLearningJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncrementalLearningJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialModel) DeepCopyInto(out *InitialModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialModel.
func (in *InitialModel) DeepCopy() *InitialModel {
	if in == nil {
		return nil
	}
	out := new(InitialModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JointInferenceService) DeepCopyInto(out *JointInferenceService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JointInferenceService.
func (in *JointInferenceService) DeepCopy() *JointInferenceService {
	if in == nil {
		return nil
	}
	out := new(JointInferenceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JointInferenceService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JointInferenceServiceCondition) DeepCopyInto(out *JointInferenceServiceCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JointInferenceServiceCondition.
func (in *JointInferenceServiceCondition) DeepCopy() *JointInferenceServiceCondition {
	if in == nil {
		return nil
	}
	out := new(JointInferenceServiceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JointInferenceServiceList) DeepCopyInto(out *JointInferenceServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JointInferenceService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JointInferenceServiceList.
func (in *JointInferenceServiceList) DeepCopy() *JointInferenceServiceList {
	if in == nil {
		return nil
	}
	out := new(JointInferenceServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JointInferenceServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JointInferenceServiceSpec) DeepCopyInto(out *JointInferenceServiceSpec) {
	*out = *in
	if in.EdgeWorker != nil {
		in, out := &in.EdgeWorker, &out.EdgeWorker
		*out = make([]EdgeWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CloudWorker.DeepCopyInto(&out.CloudWorker)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JointInferenceServiceSpec.
func (in *JointInferenceServiceSpec) DeepCopy() *JointInferenceServiceSpec {
	if in == nil {
		return nil
	}
	out := new(JointInferenceServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JointInferenceServiceStatus) DeepCopyInto(out *JointInferenceServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]JointInferenceServiceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JointInferenceServiceStatus.
func (in *JointInferenceServiceStatus) DeepCopy() *JointInferenceServiceStatus {
	if in == nil {
		return nil
	}
	out := new(JointInferenceServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLCondition) DeepCopyInto(out *LLCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLCondition.
func (in *LLCondition) DeepCopy() *LLCondition {
	if in == nil {
		return nil
	}
	out := new(LLCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLDataset) DeepCopyInto(out *LLDataset) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLDataset.
func (in *LLDataset) DeepCopy() *LLDataset {
	if in == nil {
		return nil
	}
	out := new(LLDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLDeploySpec) DeepCopyInto(out *LLDeploySpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLDeploySpec.
func (in *LLDeploySpec) DeepCopy() *LLDeploySpec {
	if in == nil {
		return nil
	}
	out := new(LLDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLEvalSpec) DeepCopyInto(out *LLEvalSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLEvalSpec.
func (in *LLEvalSpec) DeepCopy() *LLEvalSpec {
	if in == nil {
		return nil
	}
	out := new(LLEvalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLJobCondition) DeepCopyInto(out *LLJobCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLJobCondition.
func (in *LLJobCondition) DeepCopy() *LLJobCondition {
	if in == nil {
		return nil
	}
	out := new(LLJobCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLJobSpec) DeepCopyInto(out *LLJobSpec) {
	*out = *in
	out.Dataset = in.Dataset
	in.TrainSpec.DeepCopyInto(&out.TrainSpec)
	in.EvalSpec.DeepCopyInto(&out.EvalSpec)
	in.DeploySpec.DeepCopyInto(&out.DeploySpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLJobSpec.
func (in *LLJobSpec) DeepCopy() *LLJobSpec {
	if in == nil {
		return nil
	}
	out := new(LLJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLJobStatus) DeepCopyInto(out *LLJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]LLJobCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLJobStatus.
func (in *LLJobStatus) DeepCopy() *LLJobStatus {
	if in == nil {
		return nil
	}
	out := new(LLJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLTimer) DeepCopyInto(out *LLTimer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLTimer.
func (in *LLTimer) DeepCopy() *LLTimer {
	if in == nil {
		return nil
	}
	out := new(LLTimer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLTrainSpec) DeepCopyInto(out *LLTrainSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.Trigger.DeepCopyInto(&out.Trigger)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLTrainSpec.
func (in *LLTrainSpec) DeepCopy() *LLTrainSpec {
	if in == nil {
		return nil
	}
	out := new(LLTrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLTrigger) DeepCopyInto(out *LLTrigger) {
	*out = *in
	if in.Timer != nil {
		in, out := &in.Timer, &out.Timer
		*out = new(LLTimer)
		**out = **in
	}
	out.Condition = in.Condition
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLTrigger.
func (in *LLTrigger) DeepCopy() *LLTrigger {
	if in == nil {
		return nil
	}
	out := new(LLTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifelongLearningJob) DeepCopyInto(out *LifelongLearningJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifelongLearningJob.
func (in *LifelongLearningJob) DeepCopy() *LifelongLearningJob {
	if in == nil {
		return nil
	}
	out := new(LifelongLearningJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LifelongLearningJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifelongLearningJobList) DeepCopyInto(out *LifelongLearningJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LifelongLearningJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifelongLearningJobList.
func (in *LifelongLearningJobList) DeepCopy() *LifelongLearningJobList {
	if in == nil {
		return nil
	}
	out := new(LifelongLearningJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LifelongLearningJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiEdgeTrackingService) DeepCopyInto(out *MultiEdgeTrackingService) {
=======
func (in *ObjectSearchService) DeepCopyInto(out *ObjectSearchService) {
>>>>>>> sedna_github/main
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

<<<<<<< HEAD
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiEdgeTrackingService.
func (in *MultiEdgeTrackingService) DeepCopy() *MultiEdgeTrackingService {
	if in == nil {
		return nil
	}
	out := new(MultiEdgeTrackingService)
=======
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSearchService.
func (in *ObjectSearchService) DeepCopy() *ObjectSearchService {
	if in == nil {
		return nil
	}
	out := new(ObjectSearchService)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
<<<<<<< HEAD
func (in *MultiEdgeTrackingService) DeepCopyObject() runtime.Object {
=======
func (in *ObjectSearchService) DeepCopyObject() runtime.Object {
>>>>>>> sedna_github/main
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiEdgeTrackingServiceCondition) DeepCopyInto(out *MultiEdgeTrackingServiceCondition) {
=======
func (in *ObjectSearchServiceCondition) DeepCopyInto(out *ObjectSearchServiceCondition) {
>>>>>>> sedna_github/main
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

<<<<<<< HEAD
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiEdgeTrackingServiceCondition.
func (in *MultiEdgeTrackingServiceCondition) DeepCopy() *MultiEdgeTrackingServiceCondition {
	if in == nil {
		return nil
	}
	out := new(MultiEdgeTrackingServiceCondition)
=======
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSearchServiceCondition.
func (in *ObjectSearchServiceCondition) DeepCopy() *ObjectSearchServiceCondition {
	if in == nil {
		return nil
	}
	out := new(ObjectSearchServiceCondition)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiEdgeTrackingServiceList) DeepCopyInto(out *MultiEdgeTrackingServiceList) {
=======
func (in *ObjectSearchServiceList) DeepCopyInto(out *ObjectSearchServiceList) {
>>>>>>> sedna_github/main
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
<<<<<<< HEAD
		*out = make([]MultiEdgeTrackingService, len(*in))
=======
		*out = make([]ObjectSearchService, len(*in))
>>>>>>> sedna_github/main
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

<<<<<<< HEAD
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiEdgeTrackingServiceList.
func (in *MultiEdgeTrackingServiceList) DeepCopy() *MultiEdgeTrackingServiceList {
	if in == nil {
		return nil
	}
	out := new(MultiEdgeTrackingServiceList)
=======
// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSearchServiceList.
func (in *ObjectSearchServiceList) DeepCopy() *ObjectSearchServiceList {
	if in == nil {
		return nil
	}
	out := new(ObjectSearchServiceList)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
<<<<<<< HEAD
func (in *MultiEdgeTrackingServiceList) DeepCopyObject() runtime.Object {
=======
func (in *ObjectSearchServiceList) DeepCopyObject() runtime.Object {
>>>>>>> sedna_github/main
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiEdgeTrackingServiceSpec) DeepCopyInto(out *MultiEdgeTrackingServiceSpec) {
	*out = *in
	in.MultiObjectTrackingDeploy.DeepCopyInto(&out.MultiObjectTrackingDeploy)
	in.FEDeploy.DeepCopyInto(&out.FEDeploy)
	in.ReIDDeploy.DeepCopyInto(&out.ReIDDeploy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiEdgeTrackingServiceSpec.
func (in *MultiEdgeTrackingServiceSpec) DeepCopy() *MultiEdgeTrackingServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MultiEdgeTrackingServiceSpec)
=======
func (in *ObjectSearchServiceSpec) DeepCopyInto(out *ObjectSearchServiceSpec) {
	*out = *in
	in.UserWorker.DeepCopyInto(&out.UserWorker)
	if in.TrackingWorkers != nil {
		in, out := &in.TrackingWorkers, &out.TrackingWorkers
		*out = make([]TrackingWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ReidWorkers.DeepCopyInto(&out.ReidWorkers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSearchServiceSpec.
func (in *ObjectSearchServiceSpec) DeepCopy() *ObjectSearchServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectSearchServiceSpec)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiEdgeTrackingServiceStatus) DeepCopyInto(out *MultiEdgeTrackingServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MultiEdgeTrackingServiceCondition, len(*in))
=======
func (in *ObjectSearchServiceStatus) DeepCopyInto(out *ObjectSearchServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ObjectSearchServiceCondition, len(*in))
>>>>>>> sedna_github/main
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
<<<<<<< HEAD
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiEdgeTrackingServiceStatus.
func (in *MultiEdgeTrackingServiceStatus) DeepCopy() *MultiEdgeTrackingServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MultiEdgeTrackingServiceStatus)
=======
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSearchServiceStatus.
func (in *ObjectSearchServiceStatus) DeepCopy() *ObjectSearchServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectSearchServiceStatus)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *MultiObjectTrackingDeploy) DeepCopyInto(out *MultiObjectTrackingDeploy) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiObjectTrackingDeploy.
func (in *MultiObjectTrackingDeploy) DeepCopy() *MultiObjectTrackingDeploy {
	if in == nil {
		return nil
	}
	out := new(MultiObjectTrackingDeploy)
=======
func (in *ObjectTrackingService) DeepCopyInto(out *ObjectTrackingService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectTrackingService.
func (in *ObjectTrackingService) DeepCopy() *ObjectTrackingService {
	if in == nil {
		return nil
	}
	out := new(ObjectTrackingService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectTrackingService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectTrackingServiceCondition) DeepCopyInto(out *ObjectTrackingServiceCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectTrackingServiceCondition.
func (in *ObjectTrackingServiceCondition) DeepCopy() *ObjectTrackingServiceCondition {
	if in == nil {
		return nil
	}
	out := new(ObjectTrackingServiceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectTrackingServiceList) DeepCopyInto(out *ObjectTrackingServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectTrackingService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectTrackingServiceList.
func (in *ObjectTrackingServiceList) DeepCopy() *ObjectTrackingServiceList {
	if in == nil {
		return nil
	}
	out := new(ObjectTrackingServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectTrackingServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectTrackingServiceSpec) DeepCopyInto(out *ObjectTrackingServiceSpec) {
	*out = *in
	if in.TrackingWorkers != nil {
		in, out := &in.TrackingWorkers, &out.TrackingWorkers
		*out = make([]TrackingWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ReidWorkers.DeepCopyInto(&out.ReidWorkers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectTrackingServiceSpec.
func (in *ObjectTrackingServiceSpec) DeepCopy() *ObjectTrackingServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectTrackingServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectTrackingServiceStatus) DeepCopyInto(out *ObjectTrackingServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ObjectTrackingServiceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectTrackingServiceStatus.
func (in *ObjectTrackingServiceStatus) DeepCopy() *ObjectTrackingServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectTrackingServiceStatus)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParaSpec) DeepCopyInto(out *ParaSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParaSpec.
func (in *ParaSpec) DeepCopy() *ParaSpec {
	if in == nil {
		return nil
	}
	out := new(ParaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
<<<<<<< HEAD
func (in *ReIDDeploy) DeepCopyInto(out *ReIDDeploy) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReIDDeploy.
func (in *ReIDDeploy) DeepCopy() *ReIDDeploy {
	if in == nil {
		return nil
	}
	out := new(ReIDDeploy)
=======
func (in *PretrainedModel) DeepCopyInto(out *PretrainedModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PretrainedModel.
func (in *PretrainedModel) DeepCopy() *PretrainedModel {
	if in == nil {
		return nil
	}
	out := new(PretrainedModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReidWorkers) DeepCopyInto(out *ReidWorkers) {
	*out = *in
	in.DeploymentSpec.DeepCopyInto(&out.DeploymentSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReidWorkers.
func (in *ReidWorkers) DeepCopy() *ReidWorkers {
	if in == nil {
		return nil
	}
	out := new(ReidWorkers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Transmitter) DeepCopyInto(out *S3Transmitter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Transmitter.
func (in *S3Transmitter) DeepCopy() *S3Transmitter {
	if in == nil {
		return nil
	}
	out := new(S3Transmitter)
>>>>>>> sedna_github/main
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmallModel) DeepCopyInto(out *SmallModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmallModel.
func (in *SmallModel) DeepCopy() *SmallModel {
	if in == nil {
		return nil
	}
	out := new(SmallModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timer) DeepCopyInto(out *Timer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timer.
func (in *Timer) DeepCopy() *Timer {
	if in == nil {
		return nil
	}
	out := new(Timer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingWorker) DeepCopyInto(out *TrackingWorker) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingWorker.
func (in *TrackingWorker) DeepCopy() *TrackingWorker {
	if in == nil {
		return nil
	}
	out := new(TrackingWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainDataset) DeepCopyInto(out *TrainDataset) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainDataset.
func (in *TrainDataset) DeepCopy() *TrainDataset {
	if in == nil {
		return nil
	}
	out := new(TrainDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainModel) DeepCopyInto(out *TrainModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainModel.
func (in *TrainModel) DeepCopy() *TrainModel {
	if in == nil {
		return nil
	}
	out := new(TrainModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainSpec) DeepCopyInto(out *TrainSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.Trigger.DeepCopyInto(&out.Trigger)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainSpec.
func (in *TrainSpec) DeepCopy() *TrainSpec {
	if in == nil {
		return nil
	}
	out := new(TrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingWorker) DeepCopyInto(out *TrainingWorker) {
	*out = *in
	out.Dataset = in.Dataset
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingWorker.
func (in *TrainingWorker) DeepCopy() *TrainingWorker {
	if in == nil {
		return nil
	}
	out := new(TrainingWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transmitter) DeepCopyInto(out *Transmitter) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Transmitter)
		**out = **in
	}
	if in.WS != nil {
		in, out := &in.WS, &out.WS
		*out = new(WSTransmitter)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transmitter.
func (in *Transmitter) DeepCopy() *Transmitter {
	if in == nil {
		return nil
	}
	out := new(Transmitter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
	if in.Timer != nil {
		in, out := &in.Timer, &out.Timer
		*out = new(Timer)
		**out = **in
	}
	out.Condition = in.Condition
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserWorker) DeepCopyInto(out *UserWorker) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserWorker.
func (in *UserWorker) DeepCopy() *UserWorker {
	if in == nil {
		return nil
	}
	out := new(UserWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WSTransmitter) DeepCopyInto(out *WSTransmitter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WSTransmitter.
func (in *WSTransmitter) DeepCopy() *WSTransmitter {
	if in == nil {
		return nil
	}
	out := new(WSTransmitter)
	in.DeepCopyInto(out)
	return out
}
