/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kubeedge/sedna/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Datasets returns a DatasetInformer.
	Datasets() DatasetInformer
	// FeatureExtractionServices returns a FeatureExtractionServiceInformer.
	FeatureExtractionServices() FeatureExtractionServiceInformer
	// FederatedLearningJobs returns a FederatedLearningJobInformer.
	FederatedLearningJobs() FederatedLearningJobInformer
	// IncrementalLearningJobs returns a IncrementalLearningJobInformer.
	IncrementalLearningJobs() IncrementalLearningJobInformer
	// JointInferenceServices returns a JointInferenceServiceInformer.
	JointInferenceServices() JointInferenceServiceInformer
	// LifelongLearningJobs returns a LifelongLearningJobInformer.
	LifelongLearningJobs() LifelongLearningJobInformer
	// Models returns a ModelInformer.
	Models() ModelInformer
	// ObjectSearchServices returns a ObjectSearchServiceInformer.
	ObjectSearchServices() ObjectSearchServiceInformer
	// ObjectTrackingServices returns a ObjectTrackingServiceInformer.
	ObjectTrackingServices() ObjectTrackingServiceInformer
	// ReidJobs returns a ReidJobInformer.
	ReidJobs() ReidJobInformer
	// VideoAnalyticsJobs returns a VideoAnalyticsJobInformer.
	VideoAnalyticsJobs() VideoAnalyticsJobInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Datasets returns a DatasetInformer.
func (v *version) Datasets() DatasetInformer {
	return &datasetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FeatureExtractionServices returns a FeatureExtractionServiceInformer.
func (v *version) FeatureExtractionServices() FeatureExtractionServiceInformer {
	return &featureExtractionServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FederatedLearningJobs returns a FederatedLearningJobInformer.
func (v *version) FederatedLearningJobs() FederatedLearningJobInformer {
	return &federatedLearningJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IncrementalLearningJobs returns a IncrementalLearningJobInformer.
func (v *version) IncrementalLearningJobs() IncrementalLearningJobInformer {
	return &incrementalLearningJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// JointInferenceServices returns a JointInferenceServiceInformer.
func (v *version) JointInferenceServices() JointInferenceServiceInformer {
	return &jointInferenceServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LifelongLearningJobs returns a LifelongLearningJobInformer.
func (v *version) LifelongLearningJobs() LifelongLearningJobInformer {
	return &lifelongLearningJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Models returns a ModelInformer.
func (v *version) Models() ModelInformer {
	return &modelInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ObjectSearchServices returns a ObjectSearchServiceInformer.
func (v *version) ObjectSearchServices() ObjectSearchServiceInformer {
	return &objectSearchServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ObjectTrackingServices returns a ObjectTrackingServiceInformer.
func (v *version) ObjectTrackingServices() ObjectTrackingServiceInformer {
	return &objectTrackingServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ReidJobs returns a ReidJobInformer.
func (v *version) ReidJobs() ReidJobInformer {
	return &reidJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VideoAnalyticsJobs returns a VideoAnalyticsJobInformer.
func (v *version) VideoAnalyticsJobs() VideoAnalyticsJobInformer {
	return &videoAnalyticsJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
