// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kubeedge/sedna/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Datasets returns a DatasetInformer.
	Datasets() DatasetInformer
	// FederatedLearningJobs returns a FederatedLearningJobInformer.
	FederatedLearningJobs() FederatedLearningJobInformer
	// IncrementalLearningJobs returns a IncrementalLearningJobInformer.
	IncrementalLearningJobs() IncrementalLearningJobInformer
	// JointInferenceServices returns a JointInferenceServiceInformer.
	JointInferenceServices() JointInferenceServiceInformer
	// Models returns a ModelInformer.
	Models() ModelInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Datasets returns a DatasetInformer.
func (v *version) Datasets() DatasetInformer {
	return &datasetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// FederatedLearningJobs returns a FederatedLearningJobInformer.
func (v *version) FederatedLearningJobs() FederatedLearningJobInformer {
	return &federatedLearningJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IncrementalLearningJobs returns a IncrementalLearningJobInformer.
func (v *version) IncrementalLearningJobs() IncrementalLearningJobInformer {
	return &incrementalLearningJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// JointInferenceServices returns a JointInferenceServiceInformer.
func (v *version) JointInferenceServices() JointInferenceServiceInformer {
	return &jointInferenceServiceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Models returns a ModelInformer.
func (v *version) Models() ModelInformer {
	return &modelInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
