name: "movebase"
description: ""
driver:
  version: "ros1"
  type: "ros"
  name: "MoveBase"
target:
  goal: "/move_base_simple/goal"  # goal to be pusblished
  status: "/move_base/status"  # topic used to get status of movebase
  cancel: "/move_base/cancel"  # topic used to cancel the goal sent to movebase
  action: "/move_base"  # Ros action topic for movebase
  move_vel: "/cmd_vel"  # topic used to set velocity
  laserscan: "/scan"
  mapframe: "map"  # world frame name
localizer:
  algorithm: "odom"
  parameters:
    - key: "mapframe"
      value: "map"
limited:
  min_distance: 0.1
  exec_time: 0
requirement:  # Used to generate roslaunch files.
  - actionlib
  - actionlib_msgs
  - move_base_msgs
  - geometry_msgs
  - tf
