// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubeedge/sedna/pkg/apis/sedna/v1alpha1"
	scheme "github.com/kubeedge/sedna/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IncrementalLearningJobsGetter has a method to return a IncrementalLearningJobInterface.
// A group's client should implement this interface.
type IncrementalLearningJobsGetter interface {
	IncrementalLearningJobs(namespace string) IncrementalLearningJobInterface
}

// IncrementalLearningJobInterface has methods to work with IncrementalLearningJob resources.
type IncrementalLearningJobInterface interface {
	Create(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.CreateOptions) (*v1alpha1.IncrementalLearningJob, error)
	Update(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.UpdateOptions) (*v1alpha1.IncrementalLearningJob, error)
	UpdateStatus(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.UpdateOptions) (*v1alpha1.IncrementalLearningJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IncrementalLearningJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IncrementalLearningJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IncrementalLearningJob, err error)
	IncrementalLearningJobExpansion
}

// incrementalLearningJobs implements IncrementalLearningJobInterface
type incrementalLearningJobs struct {
	client rest.Interface
	ns     string
}

// newIncrementalLearningJobs returns a IncrementalLearningJobs
func newIncrementalLearningJobs(c *SednaV1alpha1Client, namespace string) *incrementalLearningJobs {
	return &incrementalLearningJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the incrementalLearningJob, and returns the corresponding incrementalLearningJob object, and an error if there is any.
func (c *incrementalLearningJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IncrementalLearningJob, err error) {
	result = &v1alpha1.IncrementalLearningJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IncrementalLearningJobs that match those selectors.
func (c *incrementalLearningJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IncrementalLearningJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IncrementalLearningJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested incrementalLearningJobs.
func (c *incrementalLearningJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a incrementalLearningJob and creates it.  Returns the server's representation of the incrementalLearningJob, and an error, if there is any.
func (c *incrementalLearningJobs) Create(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.CreateOptions) (result *v1alpha1.IncrementalLearningJob, err error) {
	result = &v1alpha1.IncrementalLearningJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(incrementalLearningJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a incrementalLearningJob and updates it. Returns the server's representation of the incrementalLearningJob, and an error, if there is any.
func (c *incrementalLearningJobs) Update(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.UpdateOptions) (result *v1alpha1.IncrementalLearningJob, err error) {
	result = &v1alpha1.IncrementalLearningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		Name(incrementalLearningJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(incrementalLearningJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *incrementalLearningJobs) UpdateStatus(ctx context.Context, incrementalLearningJob *v1alpha1.IncrementalLearningJob, opts v1.UpdateOptions) (result *v1alpha1.IncrementalLearningJob, err error) {
	result = &v1alpha1.IncrementalLearningJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		Name(incrementalLearningJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(incrementalLearningJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the incrementalLearningJob and deletes it. Returns an error if one occurs.
func (c *incrementalLearningJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *incrementalLearningJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched incrementalLearningJob.
func (c *incrementalLearningJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IncrementalLearningJob, err error) {
	result = &v1alpha1.IncrementalLearningJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("incrementallearningjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
