/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeedge/sedna/pkg/apis/sedna/v1alpha1"
	"github.com/kubeedge/sedna/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type SednaV1alpha1Interface interface {
	RESTClient() rest.Interface
	DatasetsGetter
	FeatureExtractionServicesGetter
	FederatedLearningJobsGetter
	IncrementalLearningJobsGetter
	JointInferenceServicesGetter
	LifelongLearningJobsGetter
	ModelsGetter
	ObjectSearchServicesGetter
	ObjectTrackingServicesGetter
	ReidJobsGetter
	VideoAnalyticsJobsGetter
}

// SednaV1alpha1Client is used to interact with features provided by the sedna.io group.
type SednaV1alpha1Client struct {
	restClient rest.Interface
}

func (c *SednaV1alpha1Client) Datasets(namespace string) DatasetInterface {
	return newDatasets(c, namespace)
}

func (c *SednaV1alpha1Client) FeatureExtractionServices(namespace string) FeatureExtractionServiceInterface {
	return newFeatureExtractionServices(c, namespace)
}

func (c *SednaV1alpha1Client) FederatedLearningJobs(namespace string) FederatedLearningJobInterface {
	return newFederatedLearningJobs(c, namespace)
}

func (c *SednaV1alpha1Client) IncrementalLearningJobs(namespace string) IncrementalLearningJobInterface {
	return newIncrementalLearningJobs(c, namespace)
}

func (c *SednaV1alpha1Client) JointInferenceServices(namespace string) JointInferenceServiceInterface {
	return newJointInferenceServices(c, namespace)
}

func (c *SednaV1alpha1Client) LifelongLearningJobs(namespace string) LifelongLearningJobInterface {
	return newLifelongLearningJobs(c, namespace)
}

func (c *SednaV1alpha1Client) Models(namespace string) ModelInterface {
	return newModels(c, namespace)
}

func (c *SednaV1alpha1Client) ObjectSearchServices(namespace string) ObjectSearchServiceInterface {
	return newObjectSearchServices(c, namespace)
}

func (c *SednaV1alpha1Client) ObjectTrackingServices(namespace string) ObjectTrackingServiceInterface {
	return newObjectTrackingServices(c, namespace)
}

func (c *SednaV1alpha1Client) ReidJobs(namespace string) ReidJobInterface {
	return newReidJobs(c, namespace)
}

func (c *SednaV1alpha1Client) VideoAnalyticsJobs(namespace string) VideoAnalyticsJobInterface {
	return newVideoAnalyticsJobs(c, namespace)
}

// NewForConfig creates a new SednaV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*SednaV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &SednaV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new SednaV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SednaV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new SednaV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *SednaV1alpha1Client {
	return &SednaV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SednaV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
