/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DNNPartitioningServiceListerExpansion allows custom methods to be added to
// DNNPartitioningServiceLister.
type DNNPartitioningServiceListerExpansion interface{}

// DNNPartitioningServiceNamespaceListerExpansion allows custom methods to be added to
// DNNPartitioningServiceNamespaceLister.
type DNNPartitioningServiceNamespaceListerExpansion interface{}

// DatasetListerExpansion allows custom methods to be added to
// DatasetLister.
type DatasetListerExpansion interface{}

// DatasetNamespaceListerExpansion allows custom methods to be added to
// DatasetNamespaceLister.
type DatasetNamespaceListerExpansion interface{}

// FederatedLearningJobListerExpansion allows custom methods to be added to
// FederatedLearningJobLister.
type FederatedLearningJobListerExpansion interface{}

// FederatedLearningJobNamespaceListerExpansion allows custom methods to be added to
// FederatedLearningJobNamespaceLister.
type FederatedLearningJobNamespaceListerExpansion interface{}

// IncrementalLearningJobListerExpansion allows custom methods to be added to
// IncrementalLearningJobLister.
type IncrementalLearningJobListerExpansion interface{}

// IncrementalLearningJobNamespaceListerExpansion allows custom methods to be added to
// IncrementalLearningJobNamespaceLister.
type IncrementalLearningJobNamespaceListerExpansion interface{}

// JointInferenceServiceListerExpansion allows custom methods to be added to
// JointInferenceServiceLister.
type JointInferenceServiceListerExpansion interface{}

// JointInferenceServiceNamespaceListerExpansion allows custom methods to be added to
// JointInferenceServiceNamespaceLister.
type JointInferenceServiceNamespaceListerExpansion interface{}

// LifelongLearningJobListerExpansion allows custom methods to be added to
// LifelongLearningJobLister.
type LifelongLearningJobListerExpansion interface{}

// LifelongLearningJobNamespaceListerExpansion allows custom methods to be added to
// LifelongLearningJobNamespaceLister.
type LifelongLearningJobNamespaceListerExpansion interface{}

// ModelListerExpansion allows custom methods to be added to
// ModelLister.
type ModelListerExpansion interface{}

// ModelNamespaceListerExpansion allows custom methods to be added to
// ModelNamespaceLister.
type ModelNamespaceListerExpansion interface{}

// MultiEdgeTrackingServiceListerExpansion allows custom methods to be added to
// MultiEdgeTrackingServiceLister.
type MultiEdgeTrackingServiceListerExpansion interface{}

// MultiEdgeTrackingServiceNamespaceListerExpansion allows custom methods to be added to
// MultiEdgeTrackingServiceNamespaceLister.
type MultiEdgeTrackingServiceNamespaceListerExpansion interface{}
