/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DatasetListerExpansion allows custom methods to be added to
// DatasetLister.
type DatasetListerExpansion interface{}

// DatasetNamespaceListerExpansion allows custom methods to be added to
// DatasetNamespaceLister.
type DatasetNamespaceListerExpansion interface{}

// FeatureExtractionServiceListerExpansion allows custom methods to be added to
// FeatureExtractionServiceLister.
type FeatureExtractionServiceListerExpansion interface{}

// FeatureExtractionServiceNamespaceListerExpansion allows custom methods to be added to
// FeatureExtractionServiceNamespaceLister.
type FeatureExtractionServiceNamespaceListerExpansion interface{}

// FederatedLearningJobListerExpansion allows custom methods to be added to
// FederatedLearningJobLister.
type FederatedLearningJobListerExpansion interface{}

// FederatedLearningJobNamespaceListerExpansion allows custom methods to be added to
// FederatedLearningJobNamespaceLister.
type FederatedLearningJobNamespaceListerExpansion interface{}

// IncrementalLearningJobListerExpansion allows custom methods to be added to
// IncrementalLearningJobLister.
type IncrementalLearningJobListerExpansion interface{}

// IncrementalLearningJobNamespaceListerExpansion allows custom methods to be added to
// IncrementalLearningJobNamespaceLister.
type IncrementalLearningJobNamespaceListerExpansion interface{}

// JointInferenceServiceListerExpansion allows custom methods to be added to
// JointInferenceServiceLister.
type JointInferenceServiceListerExpansion interface{}

// JointInferenceServiceNamespaceListerExpansion allows custom methods to be added to
// JointInferenceServiceNamespaceLister.
type JointInferenceServiceNamespaceListerExpansion interface{}

// LifelongLearningJobListerExpansion allows custom methods to be added to
// LifelongLearningJobLister.
type LifelongLearningJobListerExpansion interface{}

// LifelongLearningJobNamespaceListerExpansion allows custom methods to be added to
// LifelongLearningJobNamespaceLister.
type LifelongLearningJobNamespaceListerExpansion interface{}

// ModelListerExpansion allows custom methods to be added to
// ModelLister.
type ModelListerExpansion interface{}

// ModelNamespaceListerExpansion allows custom methods to be added to
// ModelNamespaceLister.
type ModelNamespaceListerExpansion interface{}

// ObjectSearchServiceListerExpansion allows custom methods to be added to
// ObjectSearchServiceLister.
type ObjectSearchServiceListerExpansion interface{}

// ObjectSearchServiceNamespaceListerExpansion allows custom methods to be added to
// ObjectSearchServiceNamespaceLister.
type ObjectSearchServiceNamespaceListerExpansion interface{}

// ObjectTrackingServiceListerExpansion allows custom methods to be added to
// ObjectTrackingServiceLister.
type ObjectTrackingServiceListerExpansion interface{}

// ObjectTrackingServiceNamespaceListerExpansion allows custom methods to be added to
// ObjectTrackingServiceNamespaceLister.
type ObjectTrackingServiceNamespaceListerExpansion interface{}

// ReidJobListerExpansion allows custom methods to be added to
// ReidJobLister.
type ReidJobListerExpansion interface{}

// ReidJobNamespaceListerExpansion allows custom methods to be added to
// ReidJobNamespaceLister.
type ReidJobNamespaceListerExpansion interface{}

// VideoAnalyticsJobListerExpansion allows custom methods to be added to
// VideoAnalyticsJobLister.
type VideoAnalyticsJobListerExpansion interface{}

// VideoAnalyticsJobNamespaceListerExpansion allows custom methods to be added to
// VideoAnalyticsJobNamespaceLister.
type VideoAnalyticsJobNamespaceListerExpansion interface{}
