// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DatasetListerExpansion allows custom methods to be added to
// DatasetLister.
type DatasetListerExpansion interface{}

// DatasetNamespaceListerExpansion allows custom methods to be added to
// DatasetNamespaceLister.
type DatasetNamespaceListerExpansion interface{}

// FederatedLearningJobListerExpansion allows custom methods to be added to
// FederatedLearningJobLister.
type FederatedLearningJobListerExpansion interface{}

// FederatedLearningJobNamespaceListerExpansion allows custom methods to be added to
// FederatedLearningJobNamespaceLister.
type FederatedLearningJobNamespaceListerExpansion interface{}

// IncrementalLearningJobListerExpansion allows custom methods to be added to
// IncrementalLearningJobLister.
type IncrementalLearningJobListerExpansion interface{}

// IncrementalLearningJobNamespaceListerExpansion allows custom methods to be added to
// IncrementalLearningJobNamespaceLister.
type IncrementalLearningJobNamespaceListerExpansion interface{}

// JointInferenceServiceListerExpansion allows custom methods to be added to
// JointInferenceServiceLister.
type JointInferenceServiceListerExpansion interface{}

// JointInferenceServiceNamespaceListerExpansion allows custom methods to be added to
// JointInferenceServiceNamespaceLister.
type JointInferenceServiceNamespaceListerExpansion interface{}

// ModelListerExpansion allows custom methods to be added to
// ModelLister.
type ModelListerExpansion interface{}

// ModelNamespaceListerExpansion allows custom methods to be added to
// ModelNamespaceLister.
type ModelNamespaceListerExpansion interface{}
