apiVersion: sedna.io/v1alpha1
kind: MultiEdgeTrackingService
metadata:
  name: containers-tracking
spec:
  multiObjectTrackingWorker:
  -  
    model:
      name: "mot-model"
    template:
      spec:
        nodeName: "frapedge00001"
        containers:
        - image: kubeedge/sedna-example-multi-edge-tracking-mot:v0.3.0
          imagePullPolicy: IfNotPresent
          name:  mot
          env:  # user defined environments
          - name: input_shape
            value: "256,128"
          - name: "video_url"
            value: "rtsp://localhost/video"
          - name: "model_name"
            value: "efficientnet_v2"
          - name: "edge_model_weights"
            value: "/data/ai_models/deep_eff_reid/weights/efficientnet_v2_model_25.pth"
          resources:  # user defined resources
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 2Gi
          volumeMounts:
            - name: outputdir
              mountPath: /data/
  - 
    model:
      name: "mot-model"
    template:
      spec:
        nodeName: "fraprigel00001"
        containers:
        - image: kubeedge/sedna-example-multi-edge-tracking-mot:v0.3.0
          imagePullPolicy: IfNotPresent
          name:  mot
          env:  # user defined environments
          - name: input_shape
            value: "256,128"
          - name: "video_url"
            value: "rtsp://localhost/video"
          - name: "model_name"
            value: "efficientnet_v2"
          - name: "edge_model_weights"
            value: "/data/ai_models/deep_eff_reid/weights/efficientnet_v2_model_25.pth"
          resources:  # user defined resources
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 2Gi
          volumeMounts:
            - name: outputdir
              mountPath: /data/

  reIDWorker:
    model:
      name: "reid-model"
    template:
      spec:
        nodeName: "fraporion00001"
        containers:
          - image: kubeedge/sedna-example-multi-edge-tracking-reid:v0.3.0
            name:  reid
            imagePullPolicy: IfNotPresent
            env:  # user defined environments
            - name: "model_name"
              value: "efficientnet_v2"
            - name: "reid_log_dir"
              value: "/data/ai_models/deep_eff_reid/loggers/runs/efficientnetv2_market_2"
            - name: "gfeats"
              value: "gfeats.pth"
            - name: "qfeats"
              value: "qfeats.pth"
            - name: "imgpath"
              value: "imgpath.npy"
            resources:  # user defined resources
              requests:
                memory: 2Gi
            volumeMounts:
            - name: outputdir
              mountPath: /data/ai_models/deep_eff_reid/loggers/runs/efficientnetv2_market_2/results/
        volumes:   # user defined volumes
          - name: outputdir
            hostPath:
              # user must create the directory in host
              path: /data/ai_models/deep_eff_reid/loggers/runs/efficientnetv2_market_2/results/
              type: Directory
